<?php

namespace App\Models;

use App\Models\Post;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes, HasFactory;

    public function posts()
    {
        return $this->hasMany(\App\Models\Post::class);
    }


    public function delete()
    {

        if ($this->id == 0) {
            echo "You can't delete this speshial category";
            return false;
        }
        \App\Models\Post::where('category_id',$this->id)->update(['category_id' => 0]);


        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
